### ISSUE TITLE
Make logo in sidebar clickable

### ISSUE THREAD

**Issue by punnypenguins** [punnypenguins/projectdelve#4]
Forgot to add this initially. Need to edit the `logo.html` file in `themes/hugo-theme-learn/layouts/partials` so when it's clicked or tapped it takes users directly to the home page.

**Comment by Fin7FW** [comment]
I think I can work on this issue.

**Comment by Dangpham0305** [comment]
Assign me. I think I can help you

**Comment by m-abdollahi** [comment]
already done that! ^_~ #11 #

**Comment by punnypenguins** [comment]
Thank you very much, @m-abdollahi!!!
